version: "3.8"
services:
  api:
    build: .
    container_name: api-backend
    ports:
      - "8004:8000"
    env_file:
      - .env
    volumes:
      - .:/app"
    depends_on:
      - db

  db:
    image: postgres:15.8
    container_name: api-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5436:5432"